// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFrfASIksijXbmrlN9i-bNyD6A0Cz8-A',
    appId: '1:206265439348:android:c4420e046c88e20e216d21',
    messagingSenderId: '206265439348',
    projectId: 'moj-majstor-a2658',
    storageBucket: 'moj-majstor-a2658.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAalv6Df1NuAmBddf4d8HFC_k-_D828Ecs',
    appId: '1:206265439348:ios:1e9694a1a80e0064216d21',
    messagingSenderId: '206265439348',
    projectId: 'moj-majstor-a2658',
    storageBucket: 'moj-majstor-a2658.appspot.com',
    iosClientId:
        '206265439348-mmdrb40cojptmj527n1vgbue8684d8l6.apps.googleusercontent.com',
    iosBundleId: 'com.moj-majstor.app',
  );
}
